language: python
cache: pip
sudo: false

matrix:
  include:
    - python: pypy-5.4.1
      env: TOXENV=pypy CODECOV=true
    - env: TOXENV=flake8

install:
  - pip install tox codecov
script:
  - tox ${CODECOV:+-- --with-coverage --cover-xml --cover-package=aplt}
after_success:
  - ${CODECOV:+codecov}
